language: android
jdk: oraclejdk8
sudo: required

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "sources;android-27"
  - yes | sdkmanager "docs"

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.1
    - android-28
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
licenses:
  - '.+'
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build

after_success:
  - ./gradlew javadocRelease

deploy:
  # Fix broken deployment due to the below issue:
  # https://github.com/travis-ci/travis-ci/issues/9312
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dynamic-engine/build/docs/javadoc/release
  on:
    branch: master